version: '3.8'
services:
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    platform: linux/amd64  
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: my-app
    ports:
      - "3001:3000"  
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://admin:admin@mongodb:27017/myapp?authSource=admin
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongodb_data: